### ISSUE TITLE
[建议] 添加网页全屏功能

### ISSUE THREAD

**Issue by AnnAngela** [Xmader/mogicians_manual#1]
里面的经典视频都不能网页全屏，又不想直接全屏，原来的大小又很小，而且观看这个效率 efficiency。

**Comment by Xmader** [comment]
请问你的浏览器是？
绝大多数浏览器在视频的进度条旁都有全屏按钮，你找一找。

**Comment by AnnAngela** [comment]
不不不，我说的是类似于B站那种在网页内全屏的功能
就是这种：
![yfzv 9xd m4e7 1xu 4 w](https://user-images.githubusercontent.com/9762652/43366656-f817b9a4-9373-11e8-99a1-2d2a070d186c.png)

**Comment by Xmader** [comment]
感谢AnnAngela，
现在已滋磁网页内全屏视频
